lambdas:
	g++ -o lambdas.exe lambdas.cpp
	./lambdas.exe
smartpointer:
	g++ -o smrtptr.exe smrtptr.cpp
	./smrtptr.exe
circular:
	g++ -o circular.exe circular.cpp
	./circular.exe
water:
	g++ -o concurrency.exe concurrency.cpp -lpthread
	./concurrency.exe