compile-game:
	g++  -o main.exe main.cpp Bishop.cpp ChessBoard.cpp ChessPiece.cpp King.cpp Knight.cpp Pawn.cpp Queen.cpp Rook.cpp
run-tests:
	g++  -o tests.exe tests.cpp Bishop.cpp ChessBoard.cpp ChessPiece.cpp King.cpp Knight.cpp Pawn.cpp Queen.cpp Rook.cpp
	./tests.exe < tests.in
run-game:
	./main.exe 